version: '3.8'
services:
    app:
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - mysql
        volumes:
            - ..:/workspace
            - ../public:/var/www/html
            - ./apache2/sites-enabled:/etc/apache2/sites-enabled:cached
        ports:
            - 5080:80

    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
        ports:
            - "5306:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '5081:80'
        restart: always
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql
